### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [4GeeksAcademy/sandrarodri_forms#1]
Feedback de Sandra:

¡Sandra, has hecho un trabajo muy bueno! Estás muy cerca del 10/10, solo necesitas pulir algunos detalles finales.

En primer lugar, es importante que arregles la parte responsive para asegurarte de que el diseño se vea correctamente tanto en dispositivos móviles como en desktop (que está logrado), pero no olvides tener en cuenta los tamaños de pantalla intermedios, como tablets, ajustando el diseño según sea necesario (col-sm col-md).

Además, es fundamental lograr que los campos "Card" y "CVC" no acepten letras y tengan una longitud máxima de 16 y 3 caracteres respectivamente. Esto ayudará a mantener la consistencia en la entrada de datos y mejorar la experiencia del usuario.

Estás muy cerca de alcanzar la perfección. ¡Sigue adelante y no te rindas! Estoy segura de que con un poco más de esfuerzo y atención a estos detalles, lograrás un proyecto impecable. ¡Ánimo y continúa trabajando duro!

---

Feedback de Adrián:

Buen trabajo! En este caso yo no creo que la visualización tablet sea tan importante, creo que cumples con lo que tienes. Sin embargo, sí veo fundamental que valides los campos Card y CVC, que ahora aceptan cualquier texto de cualquier longitud.

Otra cosa fundamental: todos los input deben tener un atributo name. En caso contrario no podemos leer sus valores desde back.

Haz esas correcciones cuando puedas!

**Comment by srdgz** [comment]
Hola @agarzon48!
Ya he modificado lo que comentas de la validación en los campos Card y CVC. En mi caso, hasta no introducir todos los campos y pulsar en Send, no aparece el mensaje para introducir el valor correcto (también he añadido un pequeño mensaje explicativo) Una vez se introduce correctamente el primer campo (Cad) y se pulsa Send, si hubiera algún campo erróneo saltaría en este momento.

En cuanto a que el formulario sea responsive, lo tengo puesto para que desde tamaño pequeño hasta md ocupe toda la pantalla.

Ya me decís.

Gracias!
